/**
 * NetworkManager - Cloudflare Worker Integration for HiveMind Network
 * 
 * Provides centralized connectivity for:
 * - Authentication (Personal Access Token + IGN)
 * - Shared Intel (KV storage via Worker API)
 * - Flood Coordination (Lock system via Worker API)
 * 
 * No Firebase SDK required. Pure fetch() calls.
 */

var NetworkManager = {
    // ===============================================================
    // CONFIGURATION
    // ===============================================================
    
    // Cloudflare Worker URL (set after deployment)
    workerUrl: "https://hivemind-worker.rhyonfs.workers.dev",
    
    // ===============================================================
    // STATE
    // ===============================================================
    
    isConnected: false,
    sessionToken: null,
    inGameName: null,
    userRole: null,
    
    // ===============================================================
    // INITIALIZATION
    // ===============================================================
    
    /**
     * Initialize NetworkManager
     * Attempts auto-login if a stored key exists
     */
    init: async function() {
        HMLogger.debug("[Network] Cloudflare NetworkManager initialized.");
        await this.autoLogin();
    },
    
    // ===============================================================
    // AUTHENTICATION
    // ===============================================================
    
    /**
     * Authenticate using Personal Access Token + In-Game Name
     * @param {string} accessToken - UUID token generated by Admin Panel
     * @returns {Promise<boolean>} - Success status
     */
    authenticate: async function(accessToken) {
        // 1. Auto-detect in-game name from DOM
        var ign = this.detectInGameName();
        if (!ign) {
            HMToast.error("Could not detect your in-game name. Are you logged in?");
            return false;
        }
        
        // 2. Call Worker /auth endpoint
        try {
            var response = await fetch(this.workerUrl + "/auth", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ ign: ign, key: accessToken })
            });
            
            if (!response.ok) {
                var error = await response.json();
                HMToast.error("Auth failed: " + (error.error || "Invalid key"));
                HMLogger.error("[Network] Auth rejected: " + (error.error || response.status));
                return false;
            }
            
            var data = await response.json();
            
            // 3. Store session
            this.sessionToken = data.token;
            this.inGameName = data.ign;
            this.userRole = data.role;
            this.isConnected = true;
            localStorage.setItem("HM_AccessToken", accessToken);
            
            // Cache the JWT session so we don't have to hit /auth constantly
            localStorage.setItem("HM_SessionToken", data.token);
            localStorage.setItem("HM_TokenExpiry", Date.now() + 86400000); // 24 hours
            localStorage.setItem("HM_SessionRole", data.role || "member");
            localStorage.setItem("HM_SessionIGN", data.ign);
            
            HMToast.success("Connected to HiveMind Network as " + data.ign);
            HMLogger.info("[Network] Authenticated: " + data.ign + " (Role: " + data.role + ")");
            return true;
            
        } catch (err) {
            HMToast.error("Network error. Check your connection.");
            HMLogger.error("[Network] Auth error: " + err.message);
            return false;
        }
    },
    
    /**
     * Auto-login using stored Personal Access Token or Cached Session
     */
    autoLogin: async function() {
        var storedKey = localStorage.getItem("HM_AccessToken");
        if (!storedKey) return false;
        
        // Fast-path: Check for valid cached JWT Session
        var sessionToken = localStorage.getItem("HM_SessionToken");
        var tokenExpiry = parseInt(localStorage.getItem("HM_TokenExpiry") || "0", 10);
        
        if (sessionToken && tokenExpiry > Date.now() + 3600000) { // Valid and > 1hr remaining
            this.sessionToken = sessionToken;
            this.inGameName = localStorage.getItem("HM_SessionIGN");
            this.userRole = localStorage.getItem("HM_SessionRole");
            this.isConnected = true;
            HMLogger.debug("[Network] Auto-connected instantly via cached session");
            return true;
        }
        
        // Slow-path: Token expired or missing, re-authenticate via Worker
        HMLogger.debug("[Network] Attempting auto-login via Worker...");
        return await this.authenticate(storedKey);
    },
    
    /**
     * Logout and clear stored credentials
     */
    logout: function() {
        this.sessionToken = null;
        this.inGameName = null;
        this.userRole = null;
        this.isConnected = false;
        localStorage.removeItem("HM_AccessToken");
        HMToast.info("Disconnected from HiveMind Network.");
    },
    
    /**
     * Detect the current user's in-game name from the DOM
     */
    detectInGameName: function() {
        // Strategy 0: Manual override from Settings
        var manual = localStorage.getItem("HM_ManualIGN");
        if (manual && manual.trim()) {
            return manual.trim();
        }
        
        // Strategy 1: .titre_ressource (e.g., "S1 Raydonia")
        var el = document.querySelector("a.titre_ressource, .titre_ressource");
        if (el && el.textContent.trim()) {
            var text = el.textContent.trim();
            // Remove server prefix like "S1 " if present
            var cleaned = text.replace(/^S\d+\s+/i, "");
            return cleaned || text;
        }
        
        // Strategy 2: #pseudo_top
        el = document.getElementById("pseudo_top");
        if (el && el.textContent.trim()) {
            return el.textContent.trim();
        }
        
        // Strategy 3: Page title
        var title = document.title;
        var match = title.match(/Colony of\s+(.+)/i) || title.match(/Colonie de\s+(.+)/i);
        if (match) {
            return match[1].trim();
        }
        
        // Strategy 4: Sidebar
        el = document.querySelector("#menuHaut .pseudo, .pseudo_joueur, #nomJoueur");
        if (el && el.textContent.trim()) {
            return el.textContent.trim();
        }
        
        // Strategy 5: FloodQueueManager
        if (typeof FloodQueueManager !== "undefined" && FloodQueueManager.getCurrentUsername) {
            var fromQueue = FloodQueueManager.getCurrentUsername();
            if (fromQueue) return fromQueue;
        }
        
        return null;
    },
    
    // ===============================================================
    // SHARED INTEL
    // ===============================================================
    
    /**
     * Submit intel report for a target
     * @param {string} targetId - Player ID
     * @param {object} data - { tdc, dome, trophies, etc. }
     */
    submitIntelReport: async function(targetId, data) {
        if (!this.isConnected) {
            HMLogger.warn("[Network] Not connected. Intel report not sent.");
            return false;
        }
        
        try {
            var response = await fetch(this.workerUrl + "/intel", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    targetId: targetId,
                    data: data,
                    submittedBy: this.inGameName
                })
            });
            
            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Intel submit error: " + err.error);
                return false;
            }
            
            HMLogger.info("[Network] Intel submitted for target: " + targetId);
            return true;
        } catch (err) {
            HMLogger.error("[Network] Intel submit error: " + err.message);
            return false;
        }
    },
    
    /**
     * Get intel for a specific target
     * @param {string} targetId 
     * @returns {object|null}
     */
    getIntelReport: async function(targetId) {
        try {
            var response = await fetch(this.workerUrl + "/intel/" + encodeURIComponent(targetId), {
                method: "GET",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            if (!response.ok) return null;
            
            return await response.json();
        } catch (err) {
            HMLogger.error("[Network] Intel fetch error: " + err.message);
            return null;
        }
    },
    
    // ===============================================================
    // FLOOD COORDINATION (Locks)
    // ===============================================================
    
    /**
     * Lock a target (indicate you are flooding it)
     * @param {string} targetId 
     * @param {string} targetName 
     */
    lockTarget: async function(targetId, targetName) {
        if (!this.isConnected) return false;
        
        try {
            var response = await fetch(this.workerUrl + "/lock", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    targetId: targetId,
                    targetName: targetName,
                    lockedBy: this.inGameName
                })
            });
            
            if (!response.ok) {
                var err = await response.json();
                HMLogger.warn("[Network] Lock failed: " + err.error);
                return false;
            }
            
            HMLogger.info("[Network] Target locked: " + targetName);
            return true;
        } catch (err) {
            HMLogger.error("[Network] Lock error: " + err.message);
            return false;
        }
    },
    
    /**
     * Unlock a target (release lock after flooding)
     * @param {string} targetId 
     */
    unlockTarget: async function(targetId) {
        if (!this.isConnected) return;
        
        try {
            await fetch(this.workerUrl + "/lock/" + encodeURIComponent(targetId), {
                method: "DELETE",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            HMLogger.info("[Network] Target unlocked: " + targetId);
        } catch (err) {
            HMLogger.error("[Network] Unlock error: " + err.message);
        }
    },
    
    /**
     * Check if a target is currently locked by someone else
     * @param {string} targetId 
     * @returns {object|null} Lock info or null if free
     */
    checkTargetLock: async function(targetId) {
        try {
            var response = await fetch(this.workerUrl + "/lock/" + encodeURIComponent(targetId), {
                method: "GET",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            if (!response.ok) return null;
            
            var data = await response.json();
            if (data.locked) {
                return {
                    lockedBy: data.locked_by,
                    lockedAt: new Date(data.locked_at)
                };
            }
            return null;
        } catch (err) {
            HMLogger.error("[Network] Lock check error: " + err.message);
            return null;
        }
    },
    
    // ===============================================================
    // HF TRACKER
    // ===============================================================
    
    /**
     * Submit HF snapshots for multiple players (batch)
     * Called automatically after scraping alliance member page
     * @param {Array} players - [{name, hf}, ...]
     * @param {string} source - "alliance_members", "ranking", "profile"
     */
    submitHFData: async function(players, source) {
        if (!this.isConnected) {
            HMLogger.debug("[Network] Not connected. HF data not submitted.");
            return false;
        }
        
        if (!players || players.length === 0) return false;
        
        try {
            var response = await fetch(this.workerUrl + "/hf/submit", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    players: players,
                    source: source || "unknown",
                    submittedBy: this.inGameName
                })
            });
            
            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] HF submit error: " + err.error);
                return false;
            }
            
            var data = await response.json();
            HMLogger.info("[Network] HF data submitted: " + data.updated + " players updated");
            return true;
        } catch (err) {
            HMLogger.error("[Network] HF submit error: " + err.message);
            return false;
        }
    },
    
    /**
     * Get HF history for a specific player
     * @param {string} playerName
     * @returns {Array} [{hf, ts, by, src}, ...]
     */
    getHFHistory: async function(playerName) {
        try {
            var response = await fetch(this.workerUrl + "/hf/history/" + encodeURIComponent(playerName), {
                method: "GET",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            if (!response.ok) return [];
            
            var data = await response.json();
            return data.history || [];
        } catch (err) {
            HMLogger.error("[Network] HF history fetch error: " + err.message);
            return [];
        }
    },
    
    /**
     * Get latest HF for all tracked players
     * @returns {Array} [{name, hf, ts, by}, ...]
     */
    getHFLatest: async function() {
        try {
            var response = await fetch(this.workerUrl + "/hf/latest", {
                method: "GET",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            if (!response.ok) return [];
            
            var data = await response.json();
            return data.players || [];
        } catch (err) {
            HMLogger.error("[Network] HF latest fetch error: " + err.message);
            return [];
        }
    },
    
    // ===============================================================
    // ENEMY INTEL
    // ===============================================================
    
    /**
     * Submit a parsed combat report for intel aggregation
     * @param {Object} report - { attacker: {name, troops, losses}, defender: {name, troops, losses}, hfStolen, outcome }
     */
    submitIntelReport: async function(report) {
        if (!this.isConnected) return false;
        
        try {
            var response = await fetch(this.workerUrl + "/intel/report", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    attacker: report.attacker,
                    defender: report.defender,
                    hfStolen: report.hfStolen,
                    outcome: report.outcome,
                    submittedBy: this.inGameName
                })
            });
            
            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Intel report error: " + err.error);
                return false;
            }
            
            HMLogger.debug("[Network] Intel report submitted successfully");
            return true;
        } catch (err) {
            HMLogger.error("[Network] Intel submit error: " + err.message);
            return false;
        }
    },

    /**
     * Submit an array of combat reports in a single batch
     * @param {Array} reports - [{attacker: {name, troops, losses}, defender: {name, troops, losses}, hfStolen, outcome, techLevels}]
     */
    submitBatchReports: async function(reports) {
        if (!this.isConnected) return false;
        if (!reports || reports.length === 0) return false;

        try {
            var response = await fetch(this.workerUrl + "/intel/reports/batch", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    reports: reports,
                    submittedBy: this.inGameName
                })
            });

            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Batch reports error: " + err.error);
                return false;
            }

            var data = await response.json();
            HMLogger.info("[Network] Batch reports submitted: " + data.reports + " reports, " + data.playersUpdated + " players updated");
            return true;
        } catch (err) {
            HMLogger.error("[Network] Batch reports error: " + err.message);
            return false;
        }
    },

    /**
     * Submit an array of player stats from the Rankings page
     * @param {Array} players - [{name, rank, hf, anthill, tech, fight}]
     */
    submitBatchIntel: async function(players) {
        if (!this.isConnected) return false;

        try {
            var response = await fetch(this.workerUrl + "/intel/batch", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify({
                    players: players,
                    submittedBy: this.inGameName
                })
            });

            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Batch Intel submit error: " + err.error);
                return false;
            }

            return true;
        } catch (err) {
            HMLogger.error("[Network] Batch Intel submit error: " + err.message);
            return false;
        }
    },

    /**
     * Submit Pacts and Wars to central intelligence
     * @param {Object} data - {pacts: [], wars: []}
     */
    submitDiplomacy: async function(data) {
        if (!this.isConnected) return false;

        try {
            var response = await fetch(this.workerUrl + "/intel/diplomacy", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify(data)
            });

            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Diplomacy submit error: " + err.error);
                return false;
            }

            return true;
        } catch (err) {
            HMLogger.error("[Network] Diplomacy submit error: " + err.message);
            return false;
        }
    },
    
    /**
     * Get aggregated intel for a player
     * @param {string} playerName
     * @returns {Object} { player, known, troops, reports, lastSeen, recentReports }
     */
    getPlayerIntel: async function(playerName) {
        try {
            var response = await fetch(this.workerUrl + "/intel/player/" + encodeURIComponent(playerName), {
                method: "GET",
                headers: { "Authorization": "Bearer " + this.sessionToken }
            });
            
            if (!response.ok) return null;
            
            return await response.json();
        } catch (err) {
            HMLogger.error("[Network] Intel fetch error: " + err.message);
            return null;
        }
    },

    // ===============================================================
    // ALLIANCE RANKINGS
    // ===============================================================

    /**
     * Submit parsed alliance rankings data
     * @param {Array} alliances - List of alliance objects {rank, name, hf, anthill, tech, fight, members}
     */
    submitAllianceRankings: async function(alliances) {
        if (!this.isConnected) return false;

        try {
            var response = await fetch(this.workerUrl + "/intel/alliances", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify(alliances)
            });

            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Alliance rankings submit error: " + err.error);
                return false;
            }

            return true;
        } catch (err) {
            HMLogger.error("[Network] Alliance rankings network error: " + err.message);
            return false;
        }
    },

    // ===============================================================
    // SPATIAL REALM MAP
    // ===============================================================

    /**
     * Submit intercepted Player X/Y Coordinates
     * @param {Array} coords - [{name: "player1", x: 12, y: 34}]
     */
    submitCoords: async function(coords) {
        if (!this.isConnected) return false;
        if (!coords || coords.length === 0) return false;

        try {
            var response = await fetch(this.workerUrl + "/intel/coords", {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "Authorization": "Bearer " + this.sessionToken
                },
                body: JSON.stringify(coords)
            });

            if (!response.ok) {
                var err = await response.json();
                HMLogger.error("[Network] Coordinates submit error: " + err.error);
                return false;
            }

            var data = await response.json();
            HMLogger.info("[Network] Coordinates permanently synced constraint map: " + data.added + " players registered");
            return true;
        } catch (err) {
            HMLogger.error("[Network] Coordinates network error: " + err.message);
            return false;
        }
    }
};
